project:
  type: website
  output-dir: _site

website:
  title: 'home |> dplyr::glimpse()'
  site-url: "https://pedro-faria.com"
  navbar:
    background: "#0e326b"
    right:
      - about.qmd
      - text: Posts
        menu:
          - text: All posts
            href: posts/index.qmd
          - text: Posts in english
            href: posts/en.qmd
          - text: Posts em português
            href: posts/pt.qmd
      - text: Publications
        menu:
          - text: All publications
            href: publications/index.qmd
          - text: Publications in English
            href: publications/en.qmd
          - text: Publicações em Português
            href: publications/pt.qmd
      - text: CV
        menu:
          - text: CV in English
            href: files/cv/cv-english.pdf
          - text: CV em Português
            href: files/cv/cv-portuguese.pdf
      - icon: envelope
        href: "mailto:pedropark99@gmail.com"
      - icon: github
        href: https://github.com/pedropark99
      - icon: twitter
        href: https://twitter.com/PedroPark9
      - icon: linkedin
        href: https://www.linkedin.com/in/pedro-faria-a68140209/


format:
  html:
    page-layout: full
    theme: 
      - cosmo
      - blue_theme.scss
    css: styles.css



