project:
  type: website

website:
  title: "Pedro Duarte Faria"
  navbar:
    left:
      - index.qmd
      - text: Posts
        menu:
          - text: All posts
            href: posts/index.qmd
          - text: English
            href: posts/en.qmd
          - text: Português
            href: posts/pt.qmd
      - publications.qmd
    right:
      - icon: github
        href: https://github.com/pedropark99
      - icon: twitter
        href: https://twitter.com/PedroPark9
      - icon: linkedin
        href: https://www.linkedin.com/in/pedro-faria-a68140209/
format:
  html:
    theme: cosmo
    css: styles.css



