project:
  type: website
  output-dir: _site

website:
  title: 'home |> dplyr::glimpse()'
  site-url: "https://pedro-faria.netlify.app/"
  description: "A blog about programming and data analysis, specially with R and Python"
  google-analytics: "G-7E6XG4WKHE"
  navbar:
    background: "#0e326b"
    right:
      - about.qmd
      - text: Posts
        menu:
          - text: All posts
            href: posts/index.qmd
          - text: Posts in english
            href: posts/en.qmd
          - text: Posts em português
            href: posts/pt.qmd
      - text: Publications
        menu:
          - text: All publications
            href: publications/index.qmd
          - text: Publications in English
            href: publications/en.qmd
          - text: Publicações em Português
            href: publications/pt.qmd
      - donate.qmd
      - text: CV
        menu:
          - text: CV in English
            href: files/cv/cv-english.pdf
          - text: CV em Português
            href: files/cv/cv-portuguese.pdf
      - icon: envelope-fill
        href: "mailto:pedropark99@gmail.com"
        aria-label: "Email for contact"
      - icon: github
        href: https://github.com/pedropark99
        aria-label: "Github profile"
      - icon: mastodon
        href: https://fosstodon.org/web/@pedropark99
        aria-label: "Mastodon profile"
      - icon: medium
        href: https://medium.com/@pedropark99
        aria-label: "Medium profile"
      - icon: twitter
        href: https://twitter.com/PedroPark9
        aria-label: "Twitter profile"
      - icon: linkedin
        href: https://www.linkedin.com/in/pedro-faria-a68140209/
        aria-label: "Linkedin profile"
      - icon: rss
        href: https://pedro-faria.netlify.app/index.xml
        aria-label: "RSS feed for Pedro's blog"


format:
  html:
    theme:
      - cosmo
      - blue_theme.scss
    css: styles.css



