project:
  type: website

website:
  title: "Pedro Duarte Faria"
  navbar:
    right:
      - posts.qmd
      - icon: github
        href: https://github.com/pedropark99
      - icon: twitter
        href: https://twitter.com/PedroPark9
      - icon: linkedin
        href: https://www.linkedin.com/in/pedro-faria-a68140209/
format:
  html:
    theme: cosmo
    css: styles.css



