---
title: "Open source contributions"
subtitle: "This is a list of my contributions to various open source projects."
title-block-banner: true
number-sections: true
---


# About this page

I love open source. So once upon a time I try to contribute to it. But
I do not have a good memory in general, so I decided to create this
page just to track down all of my contributions to various open source projects.

# My own open source projects

- [`figma`](https://github.com/pedropark99/figma): an R package that provides a R client to the Figma API.
- [`spark_map`](https://github.com/pedropark99/spark_map): a Python package to easily apply a function over multiple columns of a Spark DataFrame.
- [`ggfunnel`](https://github.com/pedropark99/ggfunnel): an R package to easily produce Power BI like funnel charts in R.

- [Introduction to pyspark](https://github.com/pedropark99/Introd-pyspark): First edition. An open source and introductory book about the Python package `pyspark`.
- [Introdução à Linguagem R: seus fundamentos e sua prática](https://github.com/pedropark99/Introducao_R): Fourth edition. An open source and introductory book (in
portuguese) about the R programming language.

# Contributions to other open source projects

## `knitr`

The `knitr` project is a general-purpose literate programming engine, and
a big open source project from the R language community.

- [PR 2140](https://github.com/yihui/knitr/pull/2140)
- [PR 2180](https://github.com/yihui/knitr/pull/2180)
- [PR 2294](https://github.com/rstudio/DT/pull/2294)

## `dev_guide`

`dev_guide` is the project for "rOpenSci Packages: Development, Maintenance, and Peer Review",
which is an open source community-driven book that describes the best practices
for development of R packages. These contributions are related to the
[Multilingual Publishing project of ROpenSci](https://ropensci.org/multilingual-publishing/).

- [PR 691](https://github.com/ropensci/dev_guide/pull/691)
- [PR 690](https://github.com/ropensci/dev_guide/pull/690)
- [PR 687](https://github.com/ropensci/dev_guide/pull/687)
- [PR 686](https://github.com/ropensci/dev_guide/pull/686)
- [PR 685](https://github.com/ropensci/dev_guide/pull/685)
- [PR 684](https://github.com/ropensci/dev_guide/pull/684)
- [PR 682](https://github.com/ropensci/dev_guide/pull/682)
- [PR 681](https://github.com/ropensci/dev_guide/pull/681)
- [PR 679](https://github.com/ropensci/dev_guide/pull/679)
- [PR 676](https://github.com/ropensci/dev_guide/pull/676)
- [PR 675](https://github.com/ropensci/dev_guide/pull/675)
- [PR 674](https://github.com/ropensci/dev_guide/pull/674)

## `DT`

`DT` is an R package that provides an R Interface to the jQuery Plug-in DataTables.

- [PR 1089](https://github.com/rstudio/DT/pull/1089)